# Generated by Django 5.0.4 on 2026-06-02 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogProject', '0003_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
