# Generated by Django 5.0.4 on 2026-06-10 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo_app_project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='priority',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=10),
        ),
    ]
